install:
    - choco install rust ruby # Install rust & ruby.
    - ps: refreshenv
    - gem install os # Install os gem.
    - rake --version
    - where cargo
    - cargo --version

test_script:
    - rake
    - rake test
