install:
    - choco install rust ruby # Install Rust & Ruby.
    - ps: refreshenv
    - gem install os # Install os gem.
    - rake --version
    - where rustc
    - where cargo

test_script:
    - rake
    - rake test
