install:
    - curl -sSf https://static.rust-lang.org/dist/rust-1.12.0-x86_64-pc-windows-gnu.msi
    #- choco install ruby
    - ps: refreshenv
    #- gem install os
    #- rake --version
    #- rustc --version
    - tree "C:\Program Files\Rust stable GNU 1.10\bin"

test_script:
    - rake
    - rake test
